### ISSUE TITLE
FileLoadException on Close

### ISSUE THREAD

**Issue by ZXX0** [stax76/mpv.net#158]
mpv.net-portable-x64-5.4.5.0.7z

If I click on X or press Esc, I get this error and then have to use task manager to end mpv:

```
FileLoadException

Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

   at mpvnet.MainForm.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at mpvnet.MainForm.WndProc(Message& m) in D:\Projekte\CS\mpv.net\mpv.net\WinForms\MainForm.cs:line 604
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by ZXX0** [comment]
mpv.net-portable-x64-5.4.4.0.7z works, probably related to #151 
i'm on win7 x64 pro

**Comment by stax76** [comment]
Please try 5.4.5.1 Beta:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta

**Comment by ZXX0** [comment]
mpv.net-portable-x64-5.4.5.1-beta.7z gives:
```
FileLoadException

Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

   at mpvnet.MainForm.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at mpvnet.MainForm.WndProc(Message& m) in D:\Projekte\CS\mpv.net\mpv.net\WinForms\MainForm.cs:line 607
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by stax76** [comment]
I don't know why it crashes because in this version it's definitivly wrapped in a try catch block.

```
            try { // PowerShell 5.1 might not be available
                foreach (PowerShell ps in PowerShell.Instances)
                    ps.Runspace.Dispose();
            } catch {}
```

Please open a powershell terminal and run:

`$PSVersionTable; [Environment]::OSVersion`

**Comment by ZXX0** [comment]
```
Name                           Value
----                           -----
CLRVersion                     2.0.50727.5485
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1

Platform      : Win32NT
ServicePack   : Service Pack 1
Version       : 6.1.7601.65536
VersionString : Microsoft Windows NT 6.1.7601 Service Pack 1
```

**Comment by stax76** [comment]
I don't have time to test this kind of issue in a VM. Next build includes another attempt to fix it, we'll see.

**Comment by ZXX0** [comment]
mpv.net-portable-x64-5.4.7.0.7z freezes up on close, then popup with:
`Shutdown thread failed to complete within 10 seconds.`
then error:
```
FileLoadException

Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

   at mpvnet.PowerShell.Shutdown()
   at mpvnet.MainForm.OnFormClosing(FormClosingEventArgs e) in D:\Projekte\CS\mpv.net\mpv.net\WinForms\MainForm.cs:line 799
   at System.Windows.Forms.Form.WmClose(Message& m)
   at mpvnet.MainForm.WndProc(Message& m) in D:\Projekte\CS\mpv.net\mpv.net\WinForms\MainForm.cs:line 610
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by stax76** [comment]
I hope it's working this time. 🤞

5.4.7.2 Beta

Changelog:

https://github.com/stax76/mpv.net/blob/master/Changelog.md

Download:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta

**Comment by ZXX0** [comment]
mpv.net-portable-x64-5.4.7.3-beta.7z > works! :smile:

**Comment by stax76** [comment]
OK, good to hear.
