### ISSUE TITLE
mpv.net 4.0.0.0 gives an ArgumentException error when minimized to taskbar

### ISSUE THREAD

**Issue by welovfree** [stax76/mpv.net#22]
**First error message:**

```
ArgumentException

Parameter is not valid.

System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at mpvnet.mp.ShowLogo() in C:\Users\frank\Daten\Projekte\CS\mpv.net\mpv.net\mpv\mp.cs:line 662
   at mpvnet.MainForm.OnResize(EventArgs e) in C:\Users\frank\Daten\Projekte\CS\mpv.net\mpv.net\WinForms\MainForm.cs:line 557
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at mpvnet.MainForm.WndProc(Message& m) in C:\Users\frank\Daten\Projekte\CS\mpv.net\mpv.net\WinForms\MainForm.cs:line 452
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
**Second error message:**

```
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at TaskDialog`1.<DialogProc>b__92_0() in C:\Users\frank\Daten\Projekte\CS\mpv.net\mpv.net\Native\TaskDialog.cs:line 418
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
![Screenshot_2](https://user-images.githubusercontent.com/47551447/58748319-5ccd4d80-8466-11e9-9a74-6c1edf20bc52.png)

**Comment by stax76** [comment]
Was it the x86 or the x64 version? Which OS are you running?

**Comment by welovfree** [comment]
mpv.net: mpv.net-setup-x64-4.0.0.0
OS: Windows 10 version 1803 (OS Build 17134.345)

**Comment by stax76** [comment]
Thanks for the feedback. What do you get with following command in PowerShell, just paste it and press enter:

$PSVersionTable.CLRVersion

**Comment by stax76** [comment]
Looks I can reproduce it! :-)

Working on a fix now.

**Comment by welovfree** [comment]
Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      30319  42000

**Comment by stax76** [comment]
Your environment is 100% identical to mine. First problem is fixed, looking at the second now and will upload a new release after it.

**Comment by stax76** [comment]
I'm not able to reproduce the crash with the clipboard, it's probably not so important because at that point there was already an unhandled exception. I'll make a new release now.

**Comment by stax76** [comment]
New release is online. Thanks for the feedback.
