### ISSUE TITLE
How to Update Portable Version 5.4.8.0 to 5.4.9.0?

### ISSUE THREAD

**Issue by CyberSolutions8799** [stax76/mpv.net#257]
When trying to update using Mpv.net Update Option it is giving me this error:

ArgumentException

Version string portion was too short or too long.

   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at mpvnet.UpdateCheck.<CheckOnline>d__1.MoveNext() in D:\Projekte\CS\mpv.net\mpv.net\Misc\UpdateCheck.cs:line 35

**Comment by stax76** [comment]
There was a breaking change in the update feature, you have to update it manually.
