### ISSUE TITLE
RatingExtension Exception on launch

### ISSUE THREAD

**Issue by Mauville** [stax76/mpv.net#280]
**Describe the bug**
Rating a video from the context menu bugs MPV.net startup to display an error. I saw a hardcoded path in the error message so I though it could be useful to open an issue. 
I installed MPV.net using choco, in Windows 10

**To Reproduce**
1. Rate a video from the context menu.
2. Close MPV
3. Reopen MPV

**Expected behavior**
MPV to start normally, without an error message.

**Error Dump**
This is the dumped error.
```

---------------------------
mpv.net
---------------------------
System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Could not load type 'mpvnet.Core' from assembly 'mpvnet, Version=5.4.9.0, Culture=neutral, PublicKeyToken=null'.

Resulting in: An exception occurred while trying to create an instance of type 'RatingExtension.RatingExtension'.

Resulting in: Cannot activate part 'RatingExtension.RatingExtension'.

Element: RatingExtension.RatingExtension -->  RatingExtension.RatingExtension -->  DirectoryCatalog (Path="C:\Program Files\mpv.net\Extensions\RatingExtension")

Resulting in: Cannot get export 'RatingExtension.RatingExtension (ContractName="mpvnet.IExtension")' from part 'RatingExtension.RatingExtension'.

Element: RatingExtension.RatingExtension (ContractName="mpvnet.IExtension") -->  RatingExtension.RatingExtension -->  DirectoryCatalog (Path="C:\Program Files\mpv.net\Extensions\RatingExtension")

Resulting in: Cannot set import 'mpvnet.Extension.Extensions (ContractName="mpvnet.IExtension")' on part 'mpvnet.Extension'.

Element: mpvnet.Extension.Extensions (ContractName="mpvnet.IExtension") -->  mpvnet.Extension
   at System.ComponentModel.Composition.CompositionResult.ThrowOnErrors(AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at mpvnet.Extension..ctor() in D:\Projekte\CS\mpv.net\src\Misc\Extension.cs:line 52
```

**Comment by hooke007** [comment]
https://github.com/stax76/mpv.net/issues/256
duplicate

**Comment by stax76** [comment]
It should be fixed in the last beta version.
