### ISSUE TITLE
font size script creating error

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#45]
Hi Stax, 

this script to set right click menu font is now creating an error, it was  working in 4.6.0.0.
I tried to read the in the commits but i'm not good at this :( i couldn't find the reason.
Here is the script:

using System;
using System.Drawing;
using mpvnet;
class Script
{
    public Script()
    {
        var form = MainForm.Instance;
        form.Invoke(new Action(() => form.ContextMenu.Font = new Font("Segoe UI", 12)));
    }
}

**Comment by stax76** [comment]
Hi, I've not changed something that could break it. Here it's still working. Which download option did you choose?

**Comment by stax76** [comment]
I tried mpv.net-portable-x64-4.7.0.0.7z and it's fine here.

**Comment by 44vince44** [comment]
I used to installer version x64. I'm gonna paste here the error in a few minutes.

**Comment by 44vince44** [comment]
Stax, I tested the 4.7.1.0 release and it is working ! the script doesn't create error anymore.
And also the autofit, start-size and remember position are working now as expected.
Though it is strange to see the tiny window opens just before video is loaded (window with size 0? only
a small bit of border appears). But all works ok! Thanks for all the work!

**Comment by 44vince44** [comment]
Well I talked too soon:
TargetInvocationException

Exception has been thrown by the target of an invocation.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at CSScriptLibrary.AsmBrowser.CreateInstance(String typeName, Object[] args)
   at CSScriptLibraryExtensionMethods.CreateObject(Assembly obj, String typeName, Object[] args)
   at CSScriptAddon.CSScriptAddon..ctor() in D:\Projekte\CS\mpv.net\addons\CSScriptAddon\CSScriptAddon.vb:line 32

**Comment by 44vince44** [comment]
OK, I taked too soon.
When I remove the font script, everything is OK. But when I put it back, the error only appears when you open a video directly from windows explorer.
If you open mpv.net, the drag and drop video, or open with key "o", that doesn't happen.

TargetInvocationException

Exception has been thrown by the target of an invocation.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
--- End of inner exception stack trace ---
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
at CSScriptLibrary.AsmBrowser.CreateInstance(String typeName, Object[] args)
at CSScriptLibraryExtensionMethods.CreateObject(Assembly obj, String typeName, Object[] args)
at CSScriptAddon.CSScriptAddon..ctor() in D:\Projekte\CS\mpv.net\addons\CSScriptAddon\CSScriptAddon.vb:line 32

**Comment by stax76** [comment]
Your feedback is greatly appreciated. The story with the tiny window is following:

I set the initial window size to being totally collapsed for render performance optimization, starting without video file this way the logo is only drawn once instead of three times, it doesn't flicker that way and it's faster.

There is thread synchronization happening, it waits 1 second to get mpv loading the video to get the video resolution needed for setting the window size, if it takes longer than you see the tiny window so it depends on the video source and the performance of your machine.

I made two changes to address this, first wait 3 seconds instead of 1 and if then the native video size is still not available I set the window size to have a normal size.

I think it's bad enough for needing another bug fix release tomorrow, for today I better quit coding, have a nice day. 🙂

**Comment by 44vince44** [comment]
Yes have some rest ;) you worked a lot today!!! Thanks :-)

**Comment by stax76** [comment]
I think I have everything covered and running smooth now, finally.

Tested fullscreen on/off, start-size video/previous, no source, video source, audio sources with and without cover art and cover art in different sizes.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

script code has changed:

```
using System;
using System.Drawing;

using mpvnet;

class Script
{
    public Script()
    {
        var form = MainForm.Instance;
        form.Shown += (object sender, EventArgs e) => form.ContextMenu.Font = new Font("Segoe UI", 12);
    }
}
```

**Comment by stax76** [comment]
I think I have everything covered and running smooth now, finally.

Tested fullscreen on/off, start-size video/previous, no source, video source, audio sources with and without cover art and cover art in different sizes.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by 44vince44** [comment]
Up to now, the version 4.7.3 is running smoothly here! no more errors, and window size is behaving as expected. Thanks !!!

**Comment by stax76** [comment]
That's good to hear though meanwhile I changed code because I thought I might be able to increase startup performance. Unfortunately I wasn't able to increase performance, the time it takes for libmpv from loading a file to being ready to play is almost a second and there probably is nothing I can do about that. It's still fast, I just wanted to ensure to do the best I possibly can.

**Comment by 44vince44** [comment]
This loading time is already much better than the players of microsoft, and others like vlc etc. So the actual performance is already a good achievement!
