### ISSUE TITLE
error on saving settings

### ISSUE THREAD

**Issue by blackarcher21** [stax76/mpv.net#74]
I have mpv.net installed from installer, not portable. I tried to change setting and it displayed this. mpv.net 5.2
![mpvnet_2019-08-07_12-52-38](https://user-images.githubusercontent.com/15969210/62595922-d96f2300-b912-11e9-95ad-9ecfee1f622f.png)

**Comment by 44vince44** [comment]
I confirm the bug, same error:


System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\mpv.net\portable_config\mpvnet.conf'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at mpvnet.ConfWindow.OnClosed(EventArgs e) in D:\Projekte\CS\mpv.net\mpv.net\WPF\ConfWindow.xaml.cs:line 132
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by stax76** [comment]
I have to make a bug fix release, a rather simple change unfortunately had caused a race condition.

**Comment by stax76** [comment]
The new release is out now and I hope it's much better than the previous one.

**Comment by blackarcher21** [comment]
thanks, thats fixes this issue here.

**Comment by 44vince44** [comment]
same here! Thanks Stax
